<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="Apps/ServiceProvider/test_create.py" name="Apps.ServiceProvider.test_create.CreateServiceProvider-20200303214930" skipped="0" tests="3" time="0.011" timestamp="2020-03-03T21:49:30">
	<testcase classname="Apps.ServiceProvider.test_create.CreateServiceProvider" file="Apps/ServiceProvider/test_create.py" line="62" name="test_create_pro_bad_date" time="0.003" timestamp="2020-03-03T21:49:30">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="Apps.ServiceProvider.test_create.CreateServiceProvider" file="Apps/ServiceProvider/test_create.py" line="23" name="test_create_service_provider_allCorrect" time="0.003" timestamp="2020-03-03T21:49:30">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="Apps.ServiceProvider.test_create.CreateServiceProvider" file="Apps/ServiceProvider/test_create.py" line="84" name="test_create_service_provider_dup_phone" time="0.005" timestamp="2020-03-03T21:49:30">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
